### ISSUE TITLE
ApplicationExtension: option for autofinding of presenters

### ISSUE THREAD

**Issue by f3l1x** [nette/application#110]
I have problem with [these lines](https://github.com/nette/application/blob/master/src/Bridges/ApplicationDI/ApplicationExtension.php#L148-L157)

```php
		$presenters = [];
		foreach (array_unique($classes) as $class) {
			if (strpos($class, $config['scanFilter']) !== FALSE && class_exists($class)
				&& ($rc = new \ReflectionClass($class)) && $rc->implementsInterface(Nette\Application\IPresenter::class)
				&& !$rc->isAbstract()
			) {
				$presenters[] = $rc->getName();
			}
		}
		return $presenters;
```

My use-case:

I have CLI application with Kdyby/Doctrine (it depends on Kdyby/Console) and there's a presenter [CliPresenter](https://github.com/Kdyby/Console/blob/master/src/Kdyby/Console/CliPresenter.php).

It requires Kdyby\Application\Console, but I have different configs on CLI deploy (without Kdyby\Console). 
It occured an Exception (`Service 'application.1': Service of type Kdyby\Console\Application needed by KdybyModule\CliPresenter::injectConsole() not found. Did you register it in configuration file`).

That's because presenters are registered by automatic.

----

It would be great have option for example **scanPresenter** for autofinding presenters. 

Does it make sence?

**Comment by enumag** [comment]
There already is an option scanComposer. If you set it to false it should fix the error.

**Comment by f3l1x** [comment]
Hmmm,

so combination scanDirs and scanComposer would solve it?

```yaml
application:
    scanDirs: []
    scanComposer: no
```

**Comment by enumag** [comment]
I scanComposer should be enough imho. Can you try it?

**Comment by f3l1x** [comment]
Sure I let you know.

**Comment by hranicka** [comment]
```yaml
application:
    scanDirs: []
```

Does not work because the default value is an array and is set internally [here](https://github.com/nette/bootstrap/blob/master/src/Bootstrap/Configurator.php#L35).

I've had a problem with DIC rebuilding in each application request (debug mode).

I use PSR-4 autoloaders everywhere (also for presenters), inspired by [Martin Zlámal](http://zlml.cz/psr-4-autoloader-aplikace). And I don't need RobotLoader to do anything.
Magic under the hood. "scanDirs" parameter is set internally, [here](https://github.com/nette/application/blob/master/src/Bridges/ApplicationDI/ApplicationExtension.php#L72). But I don't use it.

I've solved this with (bacause `scanDirs: []` doesn't work):

```yaml
application:
    scanDirs: no
```

**Comment by dg** [comment]
@f3l1x is it still valid?

**Comment by f3l1x** [comment]
@dg It's not. I know how disable `scanDirs` now, so it's ok by me. We can close it, do you agree?
