### ISSUE TITLE
Invocation of RobotLoader

### ISSUE THREAD

**Issue by jkuchar** [nette/application#78]
Shouldn't this be off by default?

gist: https://gist.github.com/jkuchar/4b349fad1a640fc13eb2

![image](https://cloud.githubusercontent.com/assets/133822/7551685/cd75bbaa-f692-11e4-9285-da27c33e0eaf.png)

**Comment by jkuchar** [comment]
Found nice workaround

````yaml
application:
	scanDirs: false

````

**Comment by fprochazka** [comment]
It should probably throw an exception, if robotloader is not installed.

**Comment by jkuchar** [comment]
I'm just curious why `$config["scanDirs"]` is by default evaluated to `true`. I'll try to print out the actualt default value. 

Here it is defined as empty array by default: https://github.com/nette/application/blob/master/src/Bridges/ApplicationDI/ApplicationExtension.php#L26

PS: Cool is that when I do not load any config anI skip over this error on Windows. Not on Linux. :smile:

**Comment by milo** [comment]
How do you register the ApplicationExtension? The Nette Bootstrap [pass](https://github.com/nette/bootstrap/blob/2850d17e91450227645c95c919d4a22d75f4e130/src/Bootstrap/Configurator.php#L39) `%appDir%`.

**Comment by hranicka** [comment]
Why is the Nette Bootstrap passes `%appDir%` and initializes Robot Loader by default?

Is it really necessary?

[In my case](https://github.com/nette/application/issues/110#issuecomment-222605730) (and I don't know why, maybe custom PresenterFactory) it causes DIC rebuild in each application request. And it's an expensive operation.

I solved this also by explicit config

```
application:
    scanDirs: no
```

But I don't why ApplicationExtension needs the RobotLoader.
I don't use it (Composer's autloader). And when, I configure and call it in [app/bootstrap.php](https://github.com/nette/sandbox/blob/master/app/bootstrap.php#L12).

Thank you.

**Comment by dg** [comment]
It is by default, because it is the most user-friendly way. If you are using a different way, you can easily disable it. 

If is DIC compiled in each request, it is a bug that needs to be addressed. Try to find reason. I think … isn't it caused by this line https://github.com/nette/application/blob/64606f4a706779bb94fc9ad06fd298eba2659bb7/src/Bridges/ApplicationDI/ApplicationExtension.php#L136?

**Comment by hranicka** [comment]
@dg I've found the temp file was touched every request, in [here](https://github.com/nette/application/blob/master/src/Bridges/ApplicationDI/PresenterFactoryCallback.php#L48).

Because the touched file is added as a [DIC dependency](https://github.com/nette/application/blob/64606f4a706779bb94fc9ad06fd298eba2659bb7/src/Bridges/ApplicationDI/ApplicationExtension.php#L136), DIC was rebuild each request.

But I've found a problem a day ago and some pages don't invokes the touch. I must study it deeply.¨¨

Maybe, I should create a new issue, identify the problem and try to find a solution how to solve it.

Thank you for kicking (positively) :-)

**Comment by dg** [comment]
It is touched when you are creating instance of presenter, which is not registered in container. But it should not touch file (see https://github.com/nette/application/blob/64606f4a706779bb94fc9ad06fd298eba2659bb7/src/Bridges/ApplicationDI/ApplicationExtension.php#L72) when `scanDirs` is false (or no).

**Comment by hranicka** [comment]
Yes, when `scanDirs` is `FALSE` it is OK and RobotLoader is not invoked and DIC is not rebuilt each request (with my custom PresenterFactory).

As I've post [above](https://github.com/nette/application/issues/78#issuecomment-222674997).

So you say the default behaviour with RobotLoader and hidden `%appDir%` is correct, OK.

Thank you.

---

**My problem is caused by a rare (?) application usage:**

* I have PSR-4 application structure, also with presenters.
* I don't use RobotLoader, but Composer's autoloader.
* I have custom PresenterFactory which allows me seperated modules loaded via Composer in different paths. _(A custom PresenterFactory may not be the reason of this issue.)_
* I don't register RobotLoader manually. But it's registered automatically by internall extension with `%appDir%` parameter. This is an underhood behaviour [here](https://github.com/nette/bootstrap/blob/master/src/Bootstrap/Configurator.php#L35) and [here](https://github.com/nette/application/blob/64606f4a706779bb94fc9ad06fd298eba2659bb7/src/Bridges/ApplicationDI/ApplicationExtension.php#L126).
* Because of [this](https://github.com/nette/application/blob/64606f4a706779bb94fc9ad06fd298eba2659bb7/src/Bridges/ApplicationDI/ApplicationExtension.php#L72), [this](https://github.com/nette/application/blob/64606f4a706779bb94fc9ad06fd298eba2659bb7/src/Bridges/ApplicationDI/ApplicationExtension.php#L136) and [this](https://github.com/nette/application/blob/master/src/Bridges/ApplicationDI/PresenterFactoryCallback.php#L48) line and custom PSR-4 presenter autoloading, the DIC is rebuilt each request.

**Fix for my PSR-4 presenters situation**:

```yaml
application:
	# PSR-4: Do not use RobotLoader nor rebuild DIC.
	scanDirs: no

	# PSR-4: Do not read classmap, it may not contains all.
	scanComposer: no
```

This also speeds up DIC building and in my case prevents rebuild each request. Which is significant improvement to me.

May helps others with some issues.

**Comment by dg** [comment]
I do not know what exactly is your motivation for this usage, but I would like to mention a couple of points
- Composer loader without --optimize is slow
- RobotLoader is extremely fast
- there is no measurable difference whether you use only Composer or Composer with RobotLoader
- RobotLoader is not *registered* by extension, it only uses with ability to find files
- creating presenter on-the-fly is slow

So when I want speed, I will use optimized Composer and presenters registered in DIC. When I want speed & comfort, I will use optimized Composer, presenters registered in DIC via extension and RobotLoader for appDir (because I don't want always call composer dumpautoload).

**Comment by hranicka** [comment]
My problem was DIC rebuilt each request. And I spent a lot of time with debugging it.
It occured because I didn't registered `scanDirs` paths for presenters in another destinations.

Ok, for performance reasons, I correctly register all paths into `scanDirs` (in local develop when use Composer and its classmap is not always created and I don't want DIC rebuilt each request or run composer --dumpautoload as you write).

And I leave `scanComposer` as-is (when Composer autoloader classmap is generated, Nette automatically registers all presenters in DIC as services => performance).

**Thank you for your help and mysterious explanation, @dg !**
