### ISSUE TITLE
Can't find Link class in API documentation

### ISSUE THREAD

**Issue by foxycode** [nette/application#82]
`Link` class description is completeley missing in Nette API documentation and not just in latest version: http://api.nette.org/2.3.3/namespace-Nette.Application.UI.html

**Comment by enumag** [comment]
It's internal class.

**Comment by foxycode** [comment]
I don't agree. It's returned by `Presenter::lazyLink`, which is public function.

**Comment by enumag** [comment]
Well it is [marked](https://github.com/nette/application/blob/master/src/Application/UI/Link.php#L18) as internal. I don't like that fact either.

**Comment by fprochazka** [comment]
@foxycode public function doesn't always mean it can't be internal. In fact it's the exact oposite. What point would have the `@internal` annotation, if not to mark public methods/classes as internal? PHP doesn't have private classes and sometimes you have to have a method public in order to achieve something - but that doesn't mean you wanna library users to use that method/class.

**Comment by foxycode** [comment]
@fprochazka I'm definitely not so experienced in OOP that many of you guys here are, but I still sense, that this class shouldn't be internal. I tried to use `lazyLink` in presenter today, got `Link` class back and couldn't find any description in API. I had to search in sources. I feel it's wrong.

**Comment by fprochazka** [comment]
@foxycode `@internal` or `private` is often used as "here is some functionality, but I don't know if I wanna implemented it this way, so probably don use this api that is marked as internal just yet" ... and then, because it was declared internal, the author of the lib can change it without creating BC Break, because he warned you it was BC Break.

On the other hand, there haven't been any development around `Link` for years and I also don't see a reason for it to be internal. Will you send a pullrequest that would remove the annotation please?

**Comment by foxycode** [comment]
@fprochazka Thanks for claryfying. PR is here: https://github.com/nette/application/pull/83

**Comment by foxycode** [comment]
Closed by https://github.com/nette/application/pull/83
